cpp/ev3dev.cpp, cpp/ev3dev.h
Hi ev3dev, first of all, thanks for putting together an awesome set of tools. This is exactly what I was hoping to find!
This PR implements a small cache of file handles for the C++ language bindings. This is discussed in issue #12. This is important to me because I'm trying to build some pretty stiff controllers. In this situation, the lower the latency (and higher the sample rate) the better.
I think that the cache should hopefully alleviate the concerns mentioned in discussion on #12 regarding caching file handles consuming too many OS resources. The global LRU cache guarantees that there will only be < FILE_CACHE_SIZE file handles open at once. I think that this PR should basically make the cases that care about performance faster (reading/writing a few attributes very frequently in a …
=> Added LRU cache of fstream objects.

.gitignore, autogen/autogen-list.json, autogen/autogen.js, autogen/templates/cpp_generic-get-set.liquid, cpp/Makefile, cpp/drive-test.cpp, cpp/ev3dev-lang-demo.cpp, cpp/ev3dev-lang-test.cpp, cpp/ev3dev.cpp, cpp/ev3dev.h, cpp/remote_control-test.cpp
This finishes the work started by @fdetro on transferring the C++ bindings to the auto-generation system (see #44, #45). 
Some changes to the existing C++ API had to be made:
1. `motor::run(bool=true)` method was renamed to `motor::start()` to avoid ambiguity with the `run` property defined in specification. See commit message to ed83fff for more details.
2. `dc_motor::command()` method was removed, since [according to the latest specification](https://github.com/ev3dev/ev3dev-lang/blob/6b43d87f8355a825b76af2c0bb3c37efacbf2820/autogen/spec.json#L52) the `command` property is write-only.
The existing implementation caches property values and sets of properties in some cases ([an example](https://github.com/ev3dev/ev3dev-lang/blob/6b43d87f8355a825b76af2c0bb3c37efacbf2820/cpp/ev3dev.cpp#L550- …
=> [cpp] Transfer the C++ bindings to the auto-generation system

.gitignore, autogen/autogen-list.json, autogen/autogen.js, autogen/templates/cpp_generic-get-set.liquid, autogen/templates/python_generic-get-set.liquid, cpp/Makefile, cpp/drive-test.cpp, cpp/ev3dev-lang-demo.cpp, cpp/ev3dev-lang-test.cpp, cpp/ev3dev.cpp, cpp/ev3dev.h, cpp/remote_control-test.cpp
This moves the python bindings to the auto-generation system. It should be merged after #47. Since python bindings live in their own repository, this PR just introduces a liquid template file for python, updates autogen-list.json, and shifts the python submodule to the latest upstream master.
=> [python] Transfer the python bindings to the auto-generation system

cpp/ev3dev.cpp, cpp/ev3dev.h
This is an incomplete PR which just updates the C++ API without touching the demos. The python bindings are based on this patch and are confirmed to work with the hardware I posses (standard mindstorms 31313 kit). 
By the way, I've just published the 0.1.0 version of the [python bindings](https://github.com/ddemidov/ev3dev-lang-python) that works with the latest kernel.
I hope to have enough time next weekend to update the C++ demos as well. In the meantime people using the C++ bindings may use this.
=> Update cpp bindings to work with the latest kernel

autogen/autogen-list.json, autogen/templates/cpp_generic_report_status.liquid, cpp/Makefile, cpp/drive-test.cpp, cpp/ev3dev-lang-demo.cpp, cpp/ev3dev-lang-test.cpp, cpp/ev3dev.h
The `ev3dev-lang-test.cpp` and `ev3dev-lang-demo.cpp` are now partially generated with the autogen system, so that they hopefully should be easier to adapt to future API changes. I had to manually comment out printing of `hold_pid/*` properties, see #53 and ev3dev/ev3dev#314.
=> [cpp][autogen] Changing the C++ demos to work with the latest API

autogen/templates/cpp_generic_report_status.liquid, cpp/ev3dev-lang-demo.cpp, cpp/ev3dev-lang-test.cpp
This changes the C++ demos to show a message instead of throwing if a property is unsupported by specific device. Example output of the `ev3dev-lang-test.cpp`:
```
Found large motor
Current properties are:
Commands: [ reset run-direct run-forever run-timed run-to-abs-pos run-to-rel-pos stop ]
Count Per Rot: 360
Driver Name: lego-ev3-l-motor
Duty Cycle: 0
Duty Cycle SP: 50
Encoder Polarity: normal
Polarity: normal
Port Name: outB
Position: 267
Position P: [not supported by the device]
Position I: [not supported by the device]
Position D: [not supported by the device]
Position SP: 100
Speed: 0
Speed SP: 0
Ramp Up SP: 0
Ramp Down SP: 0
Speed Regulation Enabled: off
Speed Regulation P: 1000
Speed Regulation I: 60
Speed Regulation D: 0
State: [ ]
Stop Command: coast
Stop Commands: [ brake …
```
=> [cpp][autogen] Show a message instead of throwing for unsupported property

cpp/ev3dev.cpp
This changes the driver name of the NXT ultrasonic sensor to
'lego-nxt-us' and alters the ev3dev::ultrasonic_sensor class constructor
to use either ev3 or nxt ultrasonic sensor.
See #45 for discussion, and thanks to @robojay for pointing at the problem and for helping with testing.
=> [cpp] Add support for NXT ultrasonic sensor

cpp/ev3dev.cpp
=> [cpp] Use either EV3 or NXT touch sensor with ev3dev::touch_sensor

cpp/ev3dev.cpp, cpp/ev3dev.h
This allows users to provide a callable that gets called on
any change in remote control buttons state. This may be useful for processing
of multi-button events.
The enum in `remote_control` class that allows to use bitwise arithmetic
for checking individual buttons state is made public (and is given a name).
=> [cpp] Expose remote control state

autogen/templates/python_generic-get-set.liquid
```python
d.command = 'run-forever'
```
is nicer than
```python
d.set_command('run_forever')
```
Also, something like this is possible:
```python
(d.speed_sp, d.time_sp, d.command) = (900, 5000, 'run-timed')
```
=> [python][autogen] Treat write-only properties as properties in python

autogen/autogen-list.json, autogen/autogen.js, autogen/spec.json, autogen/templates/cpp_generic-declare-property-value.liquid, autogen/templates/cpp_generic-define-property-value.liquid, autogen/templates/python_generic-property-value.liquid, cpp/drive-test.cpp, cpp/ev3dev-lang-demo.cpp, cpp/ev3dev-lang-test.cpp, cpp/ev3dev.cpp, cpp/ev3dev.h
This provides possible values for writable string properties in `autogen/spec.json` and uses the information to generate corresponding string constants in C++ and python API.
Some design decisions:
* The value lists are located outside of the relevant property
scopes. This is because there are several children of the sensor
class, each with own mode sets.
* Each value is represented as object instead of as simple data. This
is to allow extending the objects in the future. For example,
value description could be added for documentation purposes.
See #67 for preceding discussion.
=> [autogen][cpp][python] Add lists of possible property values to specification

autogen/autogen-list.json, autogen/autogen.js, autogen/templates/python_spec_version.liquid
This results in the following output in python:
```python
>>> import ev3dev
>>> ev3dev.__version__
0.1.1.post6 (spec: 0.9.2-pre-r3, kernel: v3.16.7-ckt10-4-ev3dev-ev3)
```
=> [autogen][python] Include spec and supported kernel versions into ev3dev.__version__

autogen/autogen-list.json, autogen/templates/python_motor_commands.liquid
This is in continuation of @dlech's [comment](https://github.com/ev3dev/ev3dev-lang/issues/51#issuecomment-98880821) in #51.
Each motor class (`tacho-motor`, `dc-motor`, `servo-motor`) provides a set of methods corresponding to possible commands. The methods take variable number of keyworded parameters. Each parameter should correspond to writable attribute of the motor. The attributes will be set before applying the command.
The methods are generated automatically based on the [list of possible commands](https://github.com/ev3dev/ev3dev-lang/blob/245b13fe8061e0ea7c0914ae9439f6c00aca7c35/autogen/spec.json#L46-L52) in `spec.json`.
Example:
```python
>>> m = large_motor()
>>> m.run_timed(time_sp=1000, duty_cycle_sp=75)
```
The second line is equivalent to
```python
>>> m.time_sp = 1000
>>> …
```
=> [autogen][py] Provide convenience functions for motor commands

autogen/templates/cpp_generic-get-set.liquid, autogen/templates/cpp_motor_commands.liquid, autogen/templates/python_generic-get-set.liquid, autogen/templates/python_motor_commands.liquid, cpp/drive-test.cpp, cpp/ev3dev.h
This is a two part change. The first part makes attribute setters return reference to the device. This makes possible chaining of setters:
```cpp
d = large_motor();
d.set_speed_regulation_enabled("on").set_speed_sp(600);
```
The second part introduces autogenerated methods corresponding to motor commands. This is similar to what was done in #75, but the methods take no arguments and just set the command attribute to the appropriate value. This may be combined with a chain of attribute setters:
```cpp
d.set_time_sp(1000).set_duty_cycle_sp(75).run_timed();
```
See the [changes to drive-test.cpp](https://github.com/ev3dev/ev3dev-lang/pull/76/files#diff-0ebd249b66f8ec55f3988d72e9476a21) for some real examples of this.
I had to change the name of "float" command for servo_motor class to
"stop" …
=> [autogen][cpp] Allow setters chaining and introduce motor commands

autogen/spec.json, autogen/templates/cpp_generic-class-description.liquid, autogen/templates/cpp_generic-declare-property-value.liquid, autogen/templates/cpp_generic-get-set.liquid, autogen/templates/md_generic-class-description.liquid, autogen/templates/md_generic-property-table.liquid, autogen/templates/python_generic-class-description.liquid, autogen/templates/python_generic-get-set.liquid, cpp/ev3dev.h, wrapper-specification.md
This adds class/property descriptions to `spec.json` and employs those for extending `wrapper-specification.md`, generating C++ comments for API functions, and generate python docstrings. The descriptions are copied from comments in [ev3dev/lego-linux-drivers](https://github.com/ev3dev/lego-linux-drivers).
The descriptions are specified in multiline format (as string lists) to allow for easy formatting of the generated code. The class descriptions are used to provide brief overview of each class in `wrapper-specification.md`.
=> Add class/property descriptions to specification

cpp/ev3dev.cpp
This adds `-q` flag to `aplay` call that is used for wav playback and for
`espeak` invocation. This suppresses the annoying output of `aplay` that
litters the ev3 screen.
=> [cpp] Suppress output of aplay command

cpp/ev3dev.cpp
This checks if attribute write was successful and throws otherwise.
The exception thrown is `std::system_error` initialized with `errno`.
See #59
=> [cpp] Throw when using unsupported attribute value

autogen/spec.json, cpp/ev3dev.cpp, cpp/ev3dev.h
The sound sensor tries to connect to a port with either `lego-nxt-sound` or `nxt-analog` driver. In case the driver is `nxt-analog`, it tries to load the correct driver through the corresponding `lego-port` class.
See the fine print here: http://www.ev3dev.org/docs/sensors/#fn:nxt-analog
Refs #59
@WasabiFan, I am not sure if this should be merged now or after the stable release, so I leave the decision to you.
=> [autogen][cpp][python] Added NXT sound and light sensors support

cpp/ev3dev.cpp, cpp/ev3dev.h
This provides user access to `bin_data_format`/`bin_data` attributes of `sensor` class in C++ and python. See ddemidov/ev3dev-lang-python#4.
In C++ its possible to ask the sensor to read raw data into a user-supplied buffer/struct:
```cpp
struct  __attribute__((__packed__)) abs_imu_data {
char tilt[3];
short accel[3];
short compass;
short mag[3];
short gyro[3];
} val;
// The get_bin_data is implemented as template:
gyro.get_bin_data(&val);
```
In python, `sensor.bin_data()` function either returns a byte buffer, or unpacked tuple:
```python
>>> from ev3dev import *
>>> ir = infrared_sensor()
>>> ir.value()
28
>>> ir.bin_data()
<read-only buffer ptr 0x3f6a58, size 1 at 0xb6a12b00>
>>> ir.bin_data('<b')
(28,)
```
=> [cpp][py] Expose sensor.bin_data attrbute

cpp/ev3dev.cpp
Path to the sensor attribute was erroneously decorated with `static` keyword, which lead to all sensors sharing same attribute. Sorry about that.
=> [cpp] Fix a bug in sensor.bin_data()

cpp/Makefile
This way you only have to assign `CROSS_COMPILE=/path/to/toolchain/arm-none-linux-gnueabi-` instead of assigning each individual variable.
=> Make cross compiling easier
